import Foundation
import AudioToolbox
import AVFoundation
import XPadCore
import XPadTheory

/// Audio Unit v3 MIDI FX Processor for DAW MIDI tracks (Logic Pro MIDI FX, Reaper, Bitwig, Cubase).
public final class XPadAUMIDIFX: XPadAudioUnitBase, @unchecked Sendable {
    public static let componentType: OSType = kAudioUnitType_MIDIProcessor // 'aumi'
    public static let componentSubType: OSType = 0x7870696D // 'xpim' (XPI MIDI FX)
    public static let componentManufacturer: OSType = 0x58504144 // 'XPAD'
    
    private var _outputBusses: AUAudioUnitBusArray!
    private var _inputBusses: AUAudioUnitBusArray!
    
    // Active sounding notes generated by the harmony processor to ensure clean release
    private var activeSoundingNotes: [UInt8: [UInt8]] = [:]
    private let voiceLeadingEngine = VoiceLeadingEngine()
    private var previousVoicing: [Note] = []
    
    public override init(
        componentDescription: AudioComponentDescription,
        options: AudioComponentInstantiationOptions = []
    ) throws {
        try super.init(componentDescription: componentDescription, options: options)
        
        self._outputBusses = AUAudioUnitBusArray(audioUnit: self, busType: .output, busses: [])
        self._inputBusses = AUAudioUnitBusArray(audioUnit: self, busType: .input, busses: [])
    }
    
    public override var outputBusses: AUAudioUnitBusArray {
        return _outputBusses
    }
    
    public override var inputBusses: AUAudioUnitBusArray {
        return _inputBusses
    }
    
    public override var internalRenderBlock: AUInternalRenderBlock {
        let midiOut = self.midiOutputEventBlock
        
        return { [weak self] actionFlags, timestamp, frameCount, outputBusNumber, outputData, realtimeEventListHead, pullInputBlock in
            guard let self = self else { return noErr }
            
            let params = self.parameterSnapshot
            let rootPitchClass = PitchClass(rawValue: Int(params.keyRoot) % 12) ?? .d
            let scaleType: ScaleType
            switch Int(params.scaleType) {
            case 0: scaleType = .major
            case 1: scaleType = .naturalMinor
            case 2: scaleType = .harmonicMinor
            case 3: scaleType = .dorian
            case 4: scaleType = .mixolydian
            case 5: scaleType = .pentatonicMajor
            default: scaleType = .pentatonicMinor
            }
            let activeScale = Scale(root: rootPitchClass, type: scaleType)
            let diatonicChords = Chord.diatonicChords(root: rootPitchClass, scale: activeScale)
            
            var eventPtr = realtimeEventListHead
            while let event = eventPtr {
                if event.pointee.head.eventType == .MIDI {
                    let midiEvent = event.pointee.MIDI
                    let status = midiEvent.data.0 & 0xF0
                    let channel = midiEvent.data.0 & 0x0F
                    let byte1 = midiEvent.data.1
                    let byte2 = midiEvent.data.2
                    
                    switch status {
                    case 0x90: // Note On
                        let inNote = byte1
                        let velocity = byte2
                        if velocity > 0 {
                            // Derive scale degree from input note
                            let pc = PitchClass(rawValue: Int(inNote) % 12) ?? .c
                            let chordToPlay: Chord
                            if let degree = activeScale.degree(of: pc), degree >= 1 && degree <= diatonicChords.count {
                                chordToPlay = diatonicChords[degree - 1]
                            } else {
                                chordToPlay = Chord(root: pc, quality: .major)
                            }
                            
                            // Apply Voice Leading
                            let targetVoicing: [Note]
                            if !self.previousVoicing.isEmpty {
                                targetVoicing = self.voiceLeadingEngine.optimizeTransition(
                                    from: self.previousVoicing,
                                    to: chordToPlay,
                                    strategy: .smooth
                                )
                            } else {
                                targetVoicing = chordToPlay.voicedNotes(baseOctave: 3)
                            }
                            self.previousVoicing = targetVoicing
                            
                            let outputMidiNotes = targetVoicing.map { $0.midiNumber }
                            self.activeSoundingNotes[inNote] = outputMidiNotes
                            
                            // Send MIDI note on for all voiced notes
                            if let outBlock = midiOut {
                                for outNote in outputMidiNotes {
                                    var msg = [UInt8(0x90 | channel), outNote, velocity]
                                    _ = outBlock(AUEventSampleTime(timestamp.pointee.mSampleTime), 0, 3, &msg)
                                }
                            }
                        } else {
                            // Note Off via vel 0
                            if let notesToRelease = self.activeSoundingNotes.removeValue(forKey: inNote),
                               let outBlock = midiOut {
                                for outNote in notesToRelease {
                                    var msg = [UInt8(0x80 | channel), outNote, 0]
                                    _ = outBlock(AUEventSampleTime(timestamp.pointee.mSampleTime), 0, 3, &msg)
                                }
                            }
                        }
                    case 0x80: // Note Off
                        let inNote = byte1
                        if let notesToRelease = self.activeSoundingNotes.removeValue(forKey: inNote),
                           let outBlock = midiOut {
                            for outNote in notesToRelease {
                                var msg = [UInt8(0x80 | channel), outNote, 0]
                                _ = outBlock(AUEventSampleTime(timestamp.pointee.mSampleTime), 0, 3, &msg)
                            }
                        }
                    default:
                        // Pass through CC, pitch bend, etc.
                        if let outBlock = midiOut {
                            var msg = [midiEvent.data.0, byte1, byte2]
                            let length = (status == 0xC0 || status == 0xD0) ? 2 : 3
                            _ = outBlock(AUEventSampleTime(timestamp.pointee.mSampleTime), 0, length, &msg)
                        }
                    }
                }
                eventPtr = event.pointee.head.next.map { UnsafePointer($0) }
            }
            
            return noErr
        }
    }
}
