import CoreMIDI
import Foundation

/// Wire protocol used by XPI's CoreMIDI virtual sources.
///
/// MIDI 1.0 remains the default compatibility path. MIDI 2.0 uses native
/// MIDI 2 Channel Voice UMP messages while preserving the same semantic
/// events generated by the rest of XPI.
public enum MIDITransportProtocol: String, CaseIterable, Identifiable, Sendable {
    case midi1 = "MIDI 1.0"
    case midi2 = "MIDI 2.0"

    public var id: String { rawValue }

    public var shortLabel: String {
        switch self {
        case .midi1: "MIDI 1"
        case .midi2: "MIDI 2"
        }
    }

    var coreMIDIProtocol: MIDIProtocolID {
        switch self {
        case .midi1: ._1_0
        case .midi2: ._2_0
        }
    }
}

/// Translates XPI's existing channel-message semantics into native MIDI 2.0
/// Channel Voice UMP. This is deliberately a transport adapter: the higher
/// layers keep working in musical units and can gain native high-resolution
/// values incrementally without duplicating the technique/MPE engine.
enum MIDI2UMPEncoder {
    static let group: UInt8 = 0

    static func message(from bytes: [UInt8]) -> MIDIMessage_64? {
        guard bytes.count == 2 || bytes.count == 3 else { return nil }

        let statusByte = bytes[0]
        let status = statusByte & 0xF0
        let channel = statusByte & 0x0F

        switch status {
        case 0x80:
            guard bytes.count == 3 else { return nil }
            return MIDI2NoteOff(
                group,
                channel,
                min(127, bytes[1]),
                0,
                0,
                scale7To16(min(127, bytes[2]))
            )

        case 0x90:
            guard bytes.count == 3 else { return nil }
            return MIDI2NoteOn(
                group,
                channel,
                min(127, bytes[1]),
                0,
                0,
                scale7To16(min(127, bytes[2]))
            )

        case 0xA0:
            guard bytes.count == 3 else { return nil }
            return MIDI2PolyPressure(
                group,
                channel,
                min(127, bytes[1]),
                scale7To32(min(127, bytes[2]))
            )

        case 0xB0:
            guard bytes.count == 3 else { return nil }
            return MIDI2ControlChange(
                group,
                channel,
                min(127, bytes[1]),
                scale7To32(min(127, bytes[2]))
            )

        case 0xD0:
            guard bytes.count == 2 else { return nil }
            return MIDI2ChannelPressure(
                group,
                channel,
                scale7To32(min(127, bytes[1]))
            )

        case 0xE0:
            guard bytes.count == 3 else { return nil }
            let value14 = UInt16(bytes[1] & 0x7F)
                | (UInt16(bytes[2] & 0x7F) << 7)
            return MIDI2PitchBend(
                group,
                channel,
                scale14BitPitchBendTo32(value14)
            )

        default:
            return nil
        }
    }

    /// Full-range conversion that preserves 0 and 127 exactly.
    static func scale7To16(_ value: UInt8) -> UInt16 {
        let clamped = UInt32(min(127, value))
        return UInt16((clamped * UInt32(UInt16.max) + 63) / 127)
    }

    /// Full-range conversion that preserves 0 and 127 exactly.
    static func scale7To32(_ value: UInt8) -> UInt32 {
        let clamped = UInt64(min(127, value))
        return UInt32((clamped * UInt64(UInt32.max) + 63) / 127)
    }

    /// Maps MIDI 1's asymmetric 14-bit pitch-bend range to MIDI 2's 32-bit
    /// range while preserving the musically critical centre point exactly.
    static func scale14BitPitchBendTo32(_ value: UInt16) -> UInt32 {
        let clamped = min(UInt16(16_383), value)
        if clamped == 8_192 { return 0x8000_0000 }

        if clamped < 8_192 {
            return UInt32(
                UInt64(clamped) * UInt64(0x8000_0000) / UInt64(8_192)
            )
        }

        return 0x8000_0000 + UInt32(
            UInt64(clamped - 8_192) * UInt64(0x7FFF_FFFF) / UInt64(8_191)
        )
    }
}
