import CoreMIDI
import Foundation
import XPadCore

/// Wire protocol used by XPI's CoreMIDI virtual sources.
///
/// MIDI 1.0 remains the default compatibility path. MIDI 2.0 uses native
/// MIDI 2 Channel Voice UMP messages while preserving the same semantic
/// events generated by the rest of XPI.
public enum MIDITransportProtocol: String, CaseIterable, Identifiable, Sendable {
    case midi1 = "MIDI 1.0"
    case midi2 = "MIDI 2.0"

    public var id: String { rawValue }

    public var shortLabel: String {
        switch self {
        case .midi1: "MIDI 1"
        case .midi2: "MIDI 2"
        }
    }

    var coreMIDIProtocol: MIDIProtocolID {
        switch self {
        case .midi1: ._1_0
        case .midi2: ._2_0
        }
    }
}

/// Translates XPI channel-message semantics into native MIDI 2.0 Channel Voice
/// UMP. Legacy byte-shaped events remain supported, while normalized/high-
/// resolution helpers allow expressive values to bypass unnecessary 7/14-bit
/// quantization when the selected transport is MIDI 2.0.
public enum MIDI2UMPEncoder {
    public static let group: UInt8 = 0
    public static let pitchBendCentre: UInt32 = 0x8000_0000

    public static func message(from bytes: [UInt8]) -> MIDIMessage_64? {
        guard bytes.count == 2 || bytes.count == 3 else { return nil }

        let statusByte = bytes[0]
        let status = statusByte & 0xF0
        let channel = statusByte & 0x0F

        switch status {
        case 0x80:
            guard bytes.count == 3 else { return nil }
            return MIDI2NoteOff(
                group,
                channel,
                min(127, bytes[1]),
                0,
                0,
                scale7To16(min(127, bytes[2]))
            )

        case 0x90:
            guard bytes.count == 3 else { return nil }
            return MIDI2NoteOn(
                group,
                channel,
                min(127, bytes[1]),
                0,
                0,
                scale7To16(min(127, bytes[2]))
            )

        case 0xA0:
            guard bytes.count == 3 else { return nil }
            return MIDI2PolyPressure(
                group,
                channel,
                min(127, bytes[1]),
                scale7To32(min(127, bytes[2]))
            )

        case 0xB0:
            guard bytes.count == 3 else { return nil }
            return MIDI2ControlChange(
                group,
                channel,
                min(127, bytes[1]),
                scale7To32(min(127, bytes[2]))
            )

        case 0xD0:
            guard bytes.count == 2 else { return nil }
            return MIDI2ChannelPressure(
                group,
                channel,
                scale7To32(min(127, bytes[1]))
            )

        case 0xE0:
            guard bytes.count == 3 else { return nil }
            let value14 = UInt16(bytes[1] & 0x7F)
                | (UInt16(bytes[2] & 0x7F) << 7)
            return MIDI2PitchBend(
                group,
                channel,
                scale14BitPitchBendTo32(value14)
            )

        default:
            return nil
        }
    }

    public static func pitchBendMessage(
        channel: UInt8,
        semitoneOffset: Double,
        bendRangeSemitones: Double
    ) -> MIDIMessage_64 {
        MIDI2PitchBend(
            group,
            min(15, channel),
            pitchBend32(
                semitoneOffset: semitoneOffset,
                bendRangeSemitones: bendRangeSemitones
            )
        )
    }

    public static func channelPressureMessage(
        channel: UInt8,
        normalizedPressure: Double
    ) -> MIDIMessage_64 {
        MIDI2ChannelPressure(
            group,
            min(15, channel),
            scaleNormalizedTo32(normalizedPressure)
        )
    }

    public static func polyPressureMessage(
        channel: UInt8,
        note: UInt8,
        normalizedPressure: Double
    ) -> MIDIMessage_64 {
        MIDI2PolyPressure(
            group,
            min(15, channel),
            min(127, note),
            scaleNormalizedTo32(normalizedPressure)
        )
    }

    public static func controlChangeMessage(
        channel: UInt8,
        controller: UInt8,
        normalizedValue: Double
    ) -> MIDIMessage_64 {
        MIDI2ControlChange(
            group,
            min(15, channel),
            min(127, controller),
            scaleNormalizedTo32(normalizedValue)
        )
    }

    // MARK: - Native MIDI 2 Per-Note Expression

    /// Generates a native 64-bit UMP Per-Note Pitch Bend message (Status 0x60).
    public static func perNotePitchBendMessage(
        channel: UInt8,
        note: UInt8,
        semitoneOffset: Double,
        bendRangeSemitones: Double
    ) -> MIDIMessage_64 {
        let pitch32 = pitchBend32(
            semitoneOffset: semitoneOffset,
            bendRangeSemitones: bendRangeSemitones
        )
        return MIDI2PerNotePitchBend(
            group,
            min(15, channel),
            min(127, note),
            pitch32
        )
    }

    /// Generates a native 64-bit UMP Per-Note Pressure (Polyphonic Aftertouch) message (Status 0xA0).
    public static func perNotePressureMessage(
        channel: UInt8,
        note: UInt8,
        normalizedPressure: Double
    ) -> MIDIMessage_64 {
        MIDI2PolyPressure(
            group,
            min(15, channel),
            min(127, note),
            scaleNormalizedTo32(normalizedPressure)
        )
    }

    /// Generates a native 64-bit UMP Registered Per-Note Controller (PNRC, Status 0x00).
    /// Used for per-note Timbre (Controller 74), Cutoff, Modulation, and Vibrato.
    public static func perNoteRegisteredControllerMessage(
        channel: UInt8,
        note: UInt8,
        controllerIndex: UInt8,
        normalizedValue: Double
    ) -> MIDIMessage_64 {
        let data32 = scaleNormalizedTo32(normalizedValue)
        let word0: UInt32 = (0x4 << 28)
            | (UInt32(group & 0x0F) << 24)
            | (0x00 << 16) // Status 0x00 = Registered Per-Note Controller
            | (UInt32(channel & 0x0F) << 16)
            | (UInt32(note & 0x7F) << 8)
            | UInt32(controllerIndex)
        return MIDIMessage_64(word0: word0, word1: data32)
    }

    /// Generates a native 64-bit UMP Per-Note Management message (Status 0xF0).
    /// Flags: bit 0 = Reset Per-Note Controllers, bit 1 = Detach Per-Note Controllers.
    public static func perNoteManagementMessage(
        channel: UInt8,
        note: UInt8,
        detach: Bool = false,
        reset: Bool = false
    ) -> MIDIMessage_64 {
        var flags: UInt8 = 0
        if reset { flags |= 0x01 }
        if detach { flags |= 0x02 }
        let word0: UInt32 = (0x4 << 28)
            | (UInt32(group & 0x0F) << 24)
            | (0xF0 << 16) // Status 0xF0 = Per-Note Management
            | (UInt32(channel & 0x0F) << 16)
            | (UInt32(note & 0x7F) << 8)
            | UInt32(flags)
        return MIDIMessage_64(word0: word0, word1: 0)
    }

    // MARK: - Note On / Note Off with 16-bit Velocity

    public static func noteOnMessage(
        channel: UInt8,
        note: UInt8,
        velocity16: UInt16,
        attributeType: UInt8 = 0,
        attributeData: UInt16 = 0
    ) -> MIDIMessage_64 {
        MIDI2NoteOn(
            group,
            min(15, channel),
            min(127, note),
            attributeType,
            velocity16,
            attributeData
        )
    }

    public static func noteOffMessage(
        channel: UInt8,
        note: UInt8,
        velocity16: UInt16 = 0,
        attributeType: UInt8 = 0,
        attributeData: UInt16 = 0
    ) -> MIDIMessage_64 {
        MIDI2NoteOff(
            group,
            min(15, channel),
            min(127, note),
            attributeType,
            velocity16,
            attributeData
        )
    }

    /// Full-range conversion that preserves 0 and 127 exactly.
    public static func scale7To16(_ value: UInt8) -> UInt16 {
        let clamped = UInt32(min(127, value))
        return UInt16((clamped * UInt32(UInt16.max) + 63) / 127)
    }

    /// Converts a 16-bit velocity to standard 7-bit MIDI velocity.
    public static func scale16To7(_ value: UInt16) -> UInt8 {
        UInt8((UInt32(value) * 127 + 32767) / UInt32(UInt16.max))
    }

    /// Converts a normalized float (0.0 ... 1.0) directly to 16-bit unsigned integer.
    public static func floatTo16Bit(_ value: Double) -> UInt16 {
        scaleNormalizedTo16(value)
    }

    /// Full-range conversion that preserves 0 and 127 exactly.
    public static func scale7To32(_ value: UInt8) -> UInt32 {
        let clamped = UInt64(min(127, value))
        return UInt32((clamped * UInt64(UInt32.max) + 63) / 127)
    }

    public static func scaleNormalizedTo16(_ value: Double) -> UInt16 {
        UInt16((value.normalizedUnit * Double(UInt16.max)).rounded())
    }

    public static func scaleNormalizedTo32(_ value: Double) -> UInt32 {
        UInt32((value.normalizedUnit * Double(UInt32.max)).rounded())
    }

    /// Maps a musical bend directly into MIDI 2's 32-bit pitch-bend field.
    /// This deliberately avoids a 14-bit intermediate so subtle vibrato/slide
    /// motion can remain distinct on MIDI 2 destinations.
    public static func pitchBend32(
        semitoneOffset: Double,
        bendRangeSemitones: Double
    ) -> UInt32 {
        guard bendRangeSemitones.isFinite, bendRangeSemitones > 0 else {
            return pitchBendCentre
        }

        let normalized = (semitoneOffset / bendRangeSemitones).normalizedBipolar
        if normalized == 0 { return pitchBendCentre }

        if normalized < 0 {
            let magnitude = UInt64(
                (-normalized * Double(UInt64(pitchBendCentre))).rounded()
            )
            return UInt32(UInt64(pitchBendCentre) - magnitude)
        }

        let positiveRange = UInt64(UInt32.max) - UInt64(pitchBendCentre)
        let magnitude = UInt64((normalized * Double(positiveRange)).rounded())
        return UInt32(UInt64(pitchBendCentre) + magnitude)
    }

    /// Maps MIDI 1's asymmetric 14-bit pitch-bend range to MIDI 2's 32-bit
    /// range while preserving the musically critical centre point exactly.
    static func scale14BitPitchBendTo32(_ value: UInt16) -> UInt32 {
        let clamped = min(UInt16(16_383), value)
        if clamped == 8_192 { return pitchBendCentre }

        if clamped < 8_192 {
            return UInt32(
                UInt64(clamped) * UInt64(pitchBendCentre) / UInt64(8_192)
            )
        }

        return pitchBendCentre + UInt32(
            UInt64(clamped - 8_192)
                * UInt64(UInt32.max - pitchBendCentre)
                / UInt64(8_191)
        )
    }

    /// Converts a 32-bit pitch-bend value to standard 14-bit pitch bend.
    public static func scale32To14BitPitchBend(_ value32: UInt32) -> UInt16 {
        if value32 == pitchBendCentre { return 8_192 }
        if value32 < pitchBendCentre {
            return UInt16((UInt64(value32) * 8_192) / UInt64(pitchBendCentre))
        }
        let positiveRange = UInt64(UInt32.max) - UInt64(pitchBendCentre)
        return 8_192 + UInt16(((UInt64(value32) - UInt64(pitchBendCentre)) * 8_191) / positiveRange)
    }

    /// Converts a 32-bit pitch bend directly to musical semitones given a bend range.
    public static func pitchBend32ToSemitones(_ value32: UInt32, bendRangeSemitones: Double) -> Double {
        guard bendRangeSemitones.isFinite, bendRangeSemitones > 0 else { return 0.0 }
        if value32 == pitchBendCentre { return 0.0 }
        if value32 < pitchBendCentre {
            let norm = -Double(UInt64(pitchBendCentre) - UInt64(value32)) / Double(pitchBendCentre)
            return norm * bendRangeSemitones
        }
        let positiveRange = UInt64(UInt32.max) - UInt64(pitchBendCentre)
        let norm = Double(UInt64(value32) - UInt64(pitchBendCentre)) / Double(positiveRange)
        return norm * bendRangeSemitones
    }

    /// Converts a 32-bit unsigned controller/pressure value to 7-bit MIDI value.
    public static func scale32To7(_ value: UInt32) -> UInt8 {
        UInt8((UInt64(value) * 127 + 0x7FFF_FFFF) / UInt64(UInt32.max))
    }

    /// Converts a 32-bit unsigned controller/pressure value to normalized 0.0...1.0.
    public static func scale32ToNormalized(_ value: UInt32) -> Double {
        Double(value) / Double(UInt32.max)
    }
}

/// Routing policy for incoming MIDI received at the virtual destination (e.g. "XPI Input / CI").
public enum MIDIPassthruMode: String, CaseIterable, Identifiable, Codable, Sendable {
    case off = "Off"
    case thruToAudio = "Synth Only"
    case thruToOutputs = "DAW Thru Only"
    case full = "Full Passthru"

    public var id: String { rawValue }

    public var routesToAudio: Bool {
        self == .thruToAudio || self == .full
    }

    public var routesToOutputs: Bool {
        self == .thruToOutputs || self == .full
    }

    public var description: String {
        switch self {
        case .off:
            "Incoming MIDI ignored (MIDI-CI discovery active)"
        case .thruToAudio:
            "Incoming MIDI triggers internal Synth Engine"
        case .thruToOutputs:
            "Incoming MIDI forwarded to DAW virtual output ports"
        case .full:
            "Incoming MIDI routed to internal Synth Engine and DAW ports"
        }
    }
}

/// Structured representation of a decoded Universal MIDI Packet (UMP).
public enum DecodedMIDIMessage: Equatable, Sendable {
    case channelVoice(event: PerformanceEvent, rawBytes: [UInt8])
    case perNotePitchBend(channel: UInt8, note: UInt8, semitoneOffset: Double, pitch32: UInt32)
    case perNotePressure(channel: UInt8, note: UInt8, normalizedPressure: Double)
    case perNoteController(channel: UInt8, note: UInt8, controller: UInt8, normalizedValue: Double)
    case perNoteManagement(channel: UInt8, note: UInt8, detach: Bool, reset: Bool)
    case sysEx(bytes: [UInt8])
    case systemRealtime(status: UInt8)
}

/// Decodes Universal MIDI Packets (UMP) into structured musical events and raw MIDI bytes.
public enum MIDI2UMPDecoder {
    public static func decode(words: [UInt32]) -> [DecodedMIDIMessage] {
        var dummyBuffer: [UInt8] = []
        return decodeStream(words: words, sysExBuffer: &dummyBuffer)
    }

    public static func decodeStream(
        words: [UInt32],
        sysExBuffer: inout [UInt8]
    ) -> [DecodedMIDIMessage] {
        var results: [DecodedMIDIMessage] = []
        var index = 0

        while index < words.count {
            let word0 = words[index]
            let messageType = (word0 >> 28) & 0x0F

            switch messageType {
            case 0x1: // System Real-Time and Common (32-bit / 1 word)
                let status = UInt8((word0 >> 16) & 0xFF)
                results.append(.systemRealtime(status: status))
                index += 1

            case 0x2: // MIDI 1.0 Channel Voice (32-bit / 1 word)
                let statusByte = UInt8((word0 >> 16) & 0xFF)
                let status = statusByte & 0xF0
                let channel = statusByte & 0x0F
                let data1 = UInt8((word0 >> 8) & 0x7F)
                let data2 = UInt8(word0 & 0x7F)

                switch status {
                case 0x80:
                    let event = PerformanceEvent.noteOff(channel: channel, note: data1)
                    results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                case 0x90:
                    if data2 == 0 {
                        let event = PerformanceEvent.noteOff(channel: channel, note: data1)
                        results.append(.channelVoice(event: event, rawBytes: [0x80 | channel, data1, 0]))
                    } else {
                        let event = PerformanceEvent.noteOn(channel: channel, note: data1, velocity: data2)
                        results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                    }
                case 0xA0:
                    let event = PerformanceEvent.polyPressure(channel: channel, note: data1, pressure: data2)
                    results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                case 0xB0:
                    if data1 == 74 {
                        let event = PerformanceEvent.timbreCC74(channel: channel, value: data2)
                        results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                    } else if data1 == 123 || data1 == 120 {
                        let event = PerformanceEvent.allNotesOff(channel: channel)
                        results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                    } else {
                        let event = PerformanceEvent.controlChange(channel: channel, controller: data1, value: data2)
                        results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                    }
                case 0xD0:
                    let event = PerformanceEvent.channelPressure(channel: channel, pressure: data1)
                    results.append(.channelVoice(event: event, rawBytes: [statusByte, data1]))
                case 0xE0:
                    let value14 = UInt16(data1) | (UInt16(data2) << 7)
                    let signedVal = Int16(Int(value14) - 8192)
                    let event = PerformanceEvent.pitchBend(channel: channel, value: signedVal)
                    results.append(.channelVoice(event: event, rawBytes: [statusByte, data1, data2]))
                default:
                    break
                }
                index += 1

            case 0x3: // 7-bit Data / SysEx (64-bit / 2 words)
                guard index + 1 < words.count else {
                    index += 1
                    break
                }
                let word1 = words[index + 1]
                let status = UInt8((word0 >> 20) & 0x0F)
                let byteCount = min(6, Int((word0 >> 16) & 0x0F))

                let rawBytesInPacket = [
                    UInt8((word0 >> 8) & 0xFF),
                    UInt8(word0 & 0xFF),
                    UInt8((word1 >> 24) & 0xFF),
                    UInt8((word1 >> 16) & 0xFF),
                    UInt8((word1 >> 8) & 0xFF),
                    UInt8(word1 & 0xFF)
                ]
                let validBytes = Array(rawBytesInPacket.prefix(byteCount))

                switch status {
                case 0: // Complete in single packet
                    results.append(.sysEx(bytes: validBytes))
                case 1: // Start
                    sysExBuffer = validBytes
                case 2: // Continue
                    sysExBuffer.append(contentsOf: validBytes)
                case 3: // End
                    sysExBuffer.append(contentsOf: validBytes)
                    results.append(.sysEx(bytes: sysExBuffer))
                    sysExBuffer.removeAll(keepingCapacity: true)
                default:
                    break
                }
                index += 2

            case 0x4: // MIDI 2.0 Channel Voice (64-bit / 2 words)
                guard index + 1 < words.count else {
                    index += 1
                    break
                }
                let word1 = words[index + 1]
                let channel = UInt8((word0 >> 16) & 0x0F)
                let opcode = UInt8((word0 >> 20) & 0x0F)
                let data1 = UInt8((word0 >> 8) & 0x7F)
                let data2 = UInt8(word0 & 0xFF)

                switch opcode {
                case 0x8: // Note Off
                    let note = data1
                    let event = PerformanceEvent.noteOff(channel: channel, note: note)
                    results.append(.channelVoice(event: event, rawBytes: [0x80 | channel, note, 0]))

                case 0x9: // Note On
                    let note = data1
                    let vel16 = UInt16(word1 & 0xFFFF)
                    let vel7 = MIDI2UMPEncoder.scale16To7(vel16)
                    if vel16 == 0 {
                        let event = PerformanceEvent.noteOff(channel: channel, note: note)
                        results.append(.channelVoice(event: event, rawBytes: [0x80 | channel, note, 0]))
                    } else {
                        let event = PerformanceEvent.noteOn(channel: channel, note: note, velocity: vel7)
                        results.append(.channelVoice(event: event, rawBytes: [0x90 | channel, note, vel7]))
                    }

                case 0xA: // Poly Pressure
                    let note = data1
                    let press7 = MIDI2UMPEncoder.scale32To7(word1)
                    let event = PerformanceEvent.polyPressure(channel: channel, note: note, pressure: press7)
                    let normPress = MIDI2UMPEncoder.scale32ToNormalized(word1)
                    results.append(.perNotePressure(channel: channel, note: note, normalizedPressure: normPress))
                    results.append(.channelVoice(event: event, rawBytes: [0xA0 | channel, note, press7]))

                case 0xB: // Control Change
                    let controller = data1
                    let val7 = MIDI2UMPEncoder.scale32To7(word1)
                    if controller == 74 {
                        let event = PerformanceEvent.timbreCC74(channel: channel, value: val7)
                        results.append(.channelVoice(event: event, rawBytes: [0xB0 | channel, controller, val7]))
                    } else if controller == 123 || controller == 120 {
                        let event = PerformanceEvent.allNotesOff(channel: channel)
                        results.append(.channelVoice(event: event, rawBytes: [0xB0 | channel, controller, 0]))
                    } else {
                        let event = PerformanceEvent.controlChange(channel: channel, controller: controller, value: val7)
                        results.append(.channelVoice(event: event, rawBytes: [0xB0 | channel, controller, val7]))
                    }

                case 0xD: // Channel Pressure
                    let press7 = MIDI2UMPEncoder.scale32To7(word1)
                    let event = PerformanceEvent.channelPressure(channel: channel, pressure: press7)
                    results.append(.channelVoice(event: event, rawBytes: [0xD0 | channel, press7]))

                case 0xE: // Pitch Bend
                    let pitch14 = MIDI2UMPEncoder.scale32To14BitPitchBend(word1)
                    let signedVal = Int16(Int(pitch14) - 8192)
                    let event = PerformanceEvent.pitchBend(channel: channel, value: signedVal)
                    results.append(.channelVoice(event: event, rawBytes: [
                        0xE0 | channel,
                        UInt8(pitch14 & 0x7F),
                        UInt8((pitch14 >> 7) & 0x7F)
                    ]))

                case 0x0: // Registered Per-Note Controller
                    let note = data1
                    let controller = data2
                    let normVal = MIDI2UMPEncoder.scale32ToNormalized(word1)
                    results.append(.perNoteController(channel: channel, note: note, controller: controller, normalizedValue: normVal))

                case 0x6: // Per-Note Pitch Bend
                    let note = data1
                    let semitones = MIDI2UMPEncoder.pitchBend32ToSemitones(word1, bendRangeSemitones: 48.0)
                    results.append(.perNotePitchBend(channel: channel, note: note, semitoneOffset: semitones, pitch32: word1))

                case 0xF: // Per-Note Management
                    let note = data1
                    let detach = (data2 & 0x02) != 0
                    let reset = (data2 & 0x01) != 0
                    results.append(.perNoteManagement(channel: channel, note: note, detach: detach, reset: reset))

                default:
                    break
                }
                index += 2

            default:
                // Skip unknown 32-bit word
                index += 1
            }
        }

        return results
    }
}
