import CoreMIDI
import Foundation

/// Wire protocol used by XPI's CoreMIDI virtual sources.
///
/// MIDI 1.0 remains the default compatibility path. MIDI 2.0 uses native
/// MIDI 2 Channel Voice UMP messages while preserving the same semantic
/// events generated by the rest of XPI.
public enum MIDITransportProtocol: String, CaseIterable, Identifiable, Sendable {
    case midi1 = "MIDI 1.0"
    case midi2 = "MIDI 2.0"

    public var id: String { rawValue }

    public var shortLabel: String {
        switch self {
        case .midi1: "MIDI 1"
        case .midi2: "MIDI 2"
        }
    }

    var coreMIDIProtocol: MIDIProtocolID {
        switch self {
        case .midi1: ._1_0
        case .midi2: ._2_0
        }
    }
}

/// Translates XPI channel-message semantics into native MIDI 2.0 Channel Voice
/// UMP. Legacy byte-shaped events remain supported, while normalized/high-
/// resolution helpers allow expressive values to bypass unnecessary 7/14-bit
/// quantization when the selected transport is MIDI 2.0.
enum MIDI2UMPEncoder {
    static let group: UInt8 = 0
    static let pitchBendCentre: UInt32 = 0x8000_0000

    static func message(from bytes: [UInt8]) -> MIDIMessage_64? {
        guard bytes.count == 2 || bytes.count == 3 else { return nil }

        let statusByte = bytes[0]
        let status = statusByte & 0xF0
        let channel = statusByte & 0x0F

        switch status {
        case 0x80:
            guard bytes.count == 3 else { return nil }
            return MIDI2NoteOff(
                group,
                channel,
                min(127, bytes[1]),
                0,
                0,
                scale7To16(min(127, bytes[2]))
            )

        case 0x90:
            guard bytes.count == 3 else { return nil }
            return MIDI2NoteOn(
                group,
                channel,
                min(127, bytes[1]),
                0,
                0,
                scale7To16(min(127, bytes[2]))
            )

        case 0xA0:
            guard bytes.count == 3 else { return nil }
            return MIDI2PolyPressure(
                group,
                channel,
                min(127, bytes[1]),
                scale7To32(min(127, bytes[2]))
            )

        case 0xB0:
            guard bytes.count == 3 else { return nil }
            return MIDI2ControlChange(
                group,
                channel,
                min(127, bytes[1]),
                scale7To32(min(127, bytes[2]))
            )

        case 0xD0:
            guard bytes.count == 2 else { return nil }
            return MIDI2ChannelPressure(
                group,
                channel,
                scale7To32(min(127, bytes[1]))
            )

        case 0xE0:
            guard bytes.count == 3 else { return nil }
            let value14 = UInt16(bytes[1] & 0x7F)
                | (UInt16(bytes[2] & 0x7F) << 7)
            return MIDI2PitchBend(
                group,
                channel,
                scale14BitPitchBendTo32(value14)
            )

        default:
            return nil
        }
    }

    static func pitchBendMessage(
        channel: UInt8,
        semitoneOffset: Double,
        bendRangeSemitones: Double
    ) -> MIDIMessage_64 {
        MIDI2PitchBend(
            group,
            min(15, channel),
            pitchBend32(
                semitoneOffset: semitoneOffset,
                bendRangeSemitones: bendRangeSemitones
            )
        )
    }

    static func channelPressureMessage(
        channel: UInt8,
        normalizedPressure: Double
    ) -> MIDIMessage_64 {
        MIDI2ChannelPressure(
            group,
            min(15, channel),
            scaleNormalizedTo32(normalizedPressure)
        )
    }

    static func polyPressureMessage(
        channel: UInt8,
        note: UInt8,
        normalizedPressure: Double
    ) -> MIDIMessage_64 {
        MIDI2PolyPressure(
            group,
            min(15, channel),
            min(127, note),
            scaleNormalizedTo32(normalizedPressure)
        )
    }

    static func controlChangeMessage(
        channel: UInt8,
        controller: UInt8,
        normalizedValue: Double
    ) -> MIDIMessage_64 {
        MIDI2ControlChange(
            group,
            min(15, channel),
            min(127, controller),
            scaleNormalizedTo32(normalizedValue)
        )
    }

    /// Full-range conversion that preserves 0 and 127 exactly.
    static func scale7To16(_ value: UInt8) -> UInt16 {
        let clamped = UInt32(min(127, value))
        return UInt16((clamped * UInt32(UInt16.max) + 63) / 127)
    }

    /// Full-range conversion that preserves 0 and 127 exactly.
    static func scale7To32(_ value: UInt8) -> UInt32 {
        let clamped = UInt64(min(127, value))
        return UInt32((clamped * UInt64(UInt32.max) + 63) / 127)
    }

    static func scaleNormalizedTo16(_ value: Double) -> UInt16 {
        guard value.isFinite else { return 0 }
        let normalized = min(1.0, max(0.0, value))
        return UInt16((normalized * Double(UInt16.max)).rounded())
    }

    static func scaleNormalizedTo32(_ value: Double) -> UInt32 {
        guard value.isFinite else { return 0 }
        let normalized = min(1.0, max(0.0, value))
        return UInt32((normalized * Double(UInt32.max)).rounded())
    }

    /// Maps a musical bend directly into MIDI 2's 32-bit pitch-bend field.
    /// This deliberately avoids a 14-bit intermediate so subtle vibrato/slide
    /// motion can remain distinct on MIDI 2 destinations.
    static func pitchBend32(
        semitoneOffset: Double,
        bendRangeSemitones: Double
    ) -> UInt32 {
        guard semitoneOffset.isFinite,
              bendRangeSemitones.isFinite,
              bendRangeSemitones > 0 else {
            return pitchBendCentre
        }

        let normalized = min(1.0, max(-1.0, semitoneOffset / bendRangeSemitones))
        if normalized == 0 { return pitchBendCentre }

        if normalized < 0 {
            let magnitude = UInt64(
                (-normalized * Double(UInt64(pitchBendCentre))).rounded()
            )
            return UInt32(UInt64(pitchBendCentre) - magnitude)
        }

        let positiveRange = UInt64(UInt32.max) - UInt64(pitchBendCentre)
        let magnitude = UInt64((normalized * Double(positiveRange)).rounded())
        return UInt32(UInt64(pitchBendCentre) + magnitude)
    }

    /// Maps MIDI 1's asymmetric 14-bit pitch-bend range to MIDI 2's 32-bit
    /// range while preserving the musically critical centre point exactly.
    static func scale14BitPitchBendTo32(_ value: UInt16) -> UInt32 {
        let clamped = min(UInt16(16_383), value)
        if clamped == 8_192 { return pitchBendCentre }

        if clamped < 8_192 {
            return UInt32(
                UInt64(clamped) * UInt64(pitchBendCentre) / UInt64(8_192)
            )
        }

        return pitchBendCentre + UInt32(
            UInt64(clamped - 8_192)
                * UInt64(UInt32.max - pitchBendCentre)
                / UInt64(8_191)
        )
    }
}
